version: '3.8'

services:
  web:
    build: .
    container_name: codeigniter_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.6
    container_name: codeigniter_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cfd
    ports:
      - "3306:3306" # Tambahkan baris ini untuk expose port
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
